In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
 

In [11]:
#fixing the dataframe 
df=pd.read_csv('vadu-dummy-data.csv',header=1)
df.head()
unique=np.array([df['Class'].unique()])
print(unique)

[['Vata' 'Kapha' 'Pitta']]


In [18]:
#initialised encoder object
encoder=OneHotEncoder(sparse_output=False)
encoded=encoder.fit_transform(df[['Class']])
print(encoded)#this is the numpy 2d array of the classes which are one hot encoded

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1.

In [21]:
#make the numpy array of the encoded classes into data frame
columns=encoder.get_feature_names_out(['Class'])
encodeddf=pd.DataFrame(encoded,columns=columns,index=df.index)
print(encodeddf)


     Class_Kapha  Class_Pitta  Class_Vata
0            0.0          0.0         1.0
1            1.0          0.0         0.0
2            0.0          0.0         1.0
3            0.0          0.0         1.0
4            1.0          0.0         0.0
..           ...          ...         ...
126          0.0          0.0         1.0
127          0.0          0.0         1.0
128          0.0          0.0         1.0
129          0.0          0.0         1.0
130          0.0          1.0         0.0

[131 rows x 3 columns]


In [25]:
final=pd.concat([df,encodeddf],axis=1)#axis=1 means concatinates columnwise
print(final)

    SampleID  Class  GENDER  ... Class_Kapha Class_Pitta Class_Vata
0         S1   Vata    Male  ...         0.0         0.0        1.0
1         S2  Kapha    Male  ...         1.0         0.0        0.0
2         S3   Vata    Male  ...         0.0         0.0        1.0
3         S4   Vata    Male  ...         0.0         0.0        1.0
4         S5  Kapha    Male  ...         1.0         0.0        0.0
..       ...    ...     ...  ...         ...         ...        ...
126     S143   Vata  Female  ...         0.0         0.0        1.0
127     S144   Vata  Female  ...         0.0         0.0        1.0
128     S145   Vata  Female  ...         0.0         0.0        1.0
129     S146   Vata  Female  ...         0.0         0.0        1.0
130     S147  Pitta  Female  ...         0.0         1.0        0.0

[131 rows x 138 columns]


In [ ]:
#i need to encode all the rows of data because all are categorical (i am cooked)